name: Daily Activity

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create random daily commits
        run: |
          mkdir -p daily-log

          # Random number between 1 and 10
          COMMITS=$((RANDOM % 10 + 1))

          echo "Today's commits: $COMMITS"

          for ((i=1; i<=COMMITS; i++))
          do
            echo "Activity $i - $(date -u '+%Y-%m-%d %H:%M:%S')" >> daily-log/activity.txt

            git config user.name "purnima20078"
          git config user.email "purni20078@gmail.com"

            git add daily-log/activity.txt
            git commit -m "Daily activity $i - $(date -u '+%Y-%m-%d')"

            sleep 2
          done

          git push
